/*
Print all subsequences of a string
Difficulty Level : Medium

Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples:

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
*/

// Java program for the above approach
import java.util.*;
class PrintAllSubsequencesRecursive{

	// Declare a global list
	static List<String> al = new ArrayList<>();

	// Creating a public static Arraylist such that
	// we can store values
	// IF there is any question of returning the
	// we can directly return too// public static
	// ArrayList<String> al = new ArrayList<String>();
	public static void main(String[] args)
	{
		String s = "abcd";
		findsubsequences(s, 0,""); // Calling a function
		System.out.println(al);
	}

	private static void findsubsequences(String s,int i,String curr)
	{
		if(i==s.length())
        {
          	al.add(curr);
          	return;
        }
      	findsubsequences(s,i+1,curr+s.charAt(i));//add
      	findsubsequences(s,i+1,curr);//don't add
	}
}
